version: 3
jobs:
  build:
    docker:
      - image: circleci/python:3.9-buster-node-browsers
        environment:
          DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/psdb
          FLASK_APP: autoapp.py
          CONDUIT_SECRET: 'something-really-secret'
          FLASK_DEBUG: 1
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: myUsr
          POSTGRES_DB: psdb
          POSTGRES_PASSWORD: somePwd
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements/dev.txt"}}-{{ .Environment.CACHE_VERSION }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
            
      - save_cache:
          key: deps-{{ checksum "requirements/dev.txt"}}-{{ .Environment.CACHE_VERSION }}
          paths: 
            - "venv"
  # test-phase:
  #   docker: 
  #     - image: circleci/python:3.9-buster-node-browsers
  #       environment:
  #         DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/psdb
  #         FLASK_APP: autoapp.py
  #         CONDUIT_SECRET: 'something-really-secret'
  #         FLASK_DEBUG: 1
  #     - image: circleci/postgres:9.6.2-alpine
  #       environment:
  #         POSTGRES_USER: myUsr
  #         POSTGRES_DB: psdb
  #         POSTGRES_PASSWORD: somePwd
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: deps-{{ checksum "requirements/dev.txt"}}-{{ .Environment.CACHE_VERSION }}
  #     - run: 
  #         command : dockerize -wait tcp://localhost:5432 -timeout 1m
  #     - run: 
  #         name: Launching tests
  #         command: |
  #           . venv/bin/activate
  #           pip install -r requirements/dev.txt
  #           python3.7 -m flask db upgrade
  #           python3.7 -m flask test
  deploy-heroku:
    docker: 
      - image : buildpack-deps:trusty
    steps:
      - checkout
      - run:
          command: |
            git config --global push.default matching
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
      - run:
          name: Smoke test
          command: |
            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/api/articles`
            if [ "$HTTPCODE" -ne 200 ];then
              echo "heroku app not responding, failing deploy"
              exit 1
            fi           
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy-heroku:
          requires: 
            - build